import type { Metadata } from "next";
import Image from "next/image";
import Button from "@/components/ui/Button";
import { aboutStories, aboutTeam, aboutTimeline, aboutValues } from "@/data/about";
import styles from "@/components/about/about-page.module.css";

export const metadata: Metadata = { title: "About" };

export default function Page() {
  return <main className={styles.page}><section className={styles.hero}><div className={styles.heroContent}><span className={styles.eyebrow}>EKO RUNNERS CLUB / ABOUT</span><h1>WE RUN<br />LAGOS.</h1></div></section><section className={styles.lead}><span className={styles.label}>WHY ERC EXISTS</span><p>Movement becomes more meaningful when you share the road.</p></section>{aboutStories.map((story) => <section className={styles.story} key={story.id}><div className={styles.storyCopy}><span className={styles.label}>{story.label}</span><h2>{story.title}</h2><p>{story.copy}</p>{story.placeholder ? <small>DEVELOPMENT CONTENT / DETAILS TBC</small> : null}</div>{story.image ? <div className={styles.storyImage}><Image src={story.image.src} alt={story.image.alt} fill sizes="(max-width: 768px) 100vw, 52vw" loading="lazy" /></div> : null}</section>)}<section className={styles.values}><h2 className={styles.label}>EVERY PACE HAS A PLACE</h2><div className={styles.valueList}>{aboutValues.map((value, index) => <article className={styles.value} key={value.id}><span>0{index + 1}</span><h3>{value.title}</h3><p>{value.copy}</p></article>)}</div></section><section className={styles.team}><h2 className={styles.label}>TEAM / FOUNDERS</h2><div className={styles.teamGrid}>{aboutTeam.map((person) => <article className={styles.person} key={person.id}><div className={styles.personImage}><Image src={person.image.src} alt={person.image.alt} fill sizes="(max-width: 768px) 72vw, 34vw" loading="lazy" /></div><h3>{person.name}</h3><p>{person.role}</p>{person.placeholder ? <small>PLACEHOLDER PROFILE / NOT ERC CONFIRMED</small> : null}</article>)}</div></section><section className={styles.timeline}><h2 className={styles.label}>TIMELINE / MILESTONES</h2><div className={styles.timelineList}>{aboutTimeline.map((item) => <article className={styles.milestone} key={item.id}><span>{item.date}</span><strong>{item.title}</strong><small>{item.copy}</small></article>)}</div></section><section className={styles.join}><h2>COME RUN WITH US.</h2><Button href="/runs" arrow>JOIN THE COMMUNITY</Button></section></main>;
}
