import type { Metadata } from "next";
import Image from "next/image";
import Button from "@/components/ui/Button";
import { confirmedCollaborations, partnershipFormats, partnershipReach } from "@/data/partnerships";
import styles from "@/components/partners/partners-page.module.css";

export const metadata: Metadata = { title: "Partners" };

export default function Page() {
  return <main className={styles.page}><section className={styles.hero}><div className={styles.heroContent}><span className={styles.eyebrow}>EKO RUNNERS CLUB / PARTNERSHIPS</span><h1>MOVE<br />WITH<br />EKO.</h1></div></section><section className={styles.proposition}><h2>Want to build something with the people moving Lagos?</h2><p>ERC creates space for brands to meet a real running community through movement, culture and physical experiences. Partnership formats remain flexible and are shaped around the people involved.</p></section><section className={styles.why}><h2 className={styles.label}>WHY ERC</h2><div className={styles.whyGrid}>{["COMMUNITY", "CULTURE", "PHYSICAL EVENTS", "LAGOS PRESENCE", "AUTHENTIC ENGAGEMENT"].map((item) => <article className={styles.whyItem} key={item}><strong>{item}</strong><p>Partnership proposition detail to be developed with ERC.</p></article>)}</div></section><section className={styles.formats}><h2 className={styles.label}>WAYS TO PARTNER</h2><div className={styles.formatList}>{partnershipFormats.map((format, index) => <article className={styles.format} key={format.id}><span>0{index + 1}</span><h3>{format.title}</h3><p>{format.description}</p></article>)}</div></section><section className={styles.collabs}><h2 className={styles.label}>PREVIOUS COLLABORATIONS</h2>{confirmedCollaborations.length ? <div>{confirmedCollaborations.map((item) => <p key={item}>{item}</p>)}</div> : <p className={styles.collabEmpty}>Confirmed collaboration records will appear here when supplied.</p>}</section><section className={styles.activation}><h2>AN ACTIVATION SHOULD FEEL LIKE ERC.</h2><p>From first idea to the moment people leave, a partnership can move through a run, an event, a recovery session or a story. Case study details will be added after a confirmed activation.</p></section><section className={styles.reach}><h2 className={styles.label}>COMMUNITY REACH</h2><div className={styles.reachGrid}>{partnershipReach.map((item) => <div className={styles.reachItem} key={item.id}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></section><section className={styles.gallery}><h2 className={styles.label}>PARTNERSHIP GALLERY</h2><div className={styles.galleryGrid}><Image src="/images/image (25).jpg" alt="Eko Runners community gathering placeholder" width={1600} height={1000} sizes="(max-width: 768px) 100vw, 60vw" loading="lazy" /><Image src="/images/image (20).jpg" alt="Eko Runners portrait placeholder" width={1200} height={1600} sizes="(max-width: 768px) 70vw, 30vw" loading="lazy" /></div></section><section className={styles.cta}><h2>BUILD SOMETHING WITH THE PEOPLE MOVING LAGOS.</h2><Button href="/partners" arrow>PARTNER WITH ERC</Button></section></main>;
}
